using System;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Audio;
using Microsoft.Xna.Framework.Graphics;
using Monsterfall_01.Engine.StateManager;
using Monsterfall_01.Engine.UI;


namespace Monsterfall_01.StatesMenu
{
    internal class StateMenuMain : State
    {
        // List of buttons to select
        private ButtonList ButtonList;

        // Buttons sound effects   
        SoundEffectInstance switchSound;
        SoundEffectInstance selectSound;

        // Events generated by clicking buttons
        public event EventHandler GameStart;
        public event EventHandler HighScores;
        public event EventHandler Controls;
        public event EventHandler ExitGame;
        public StateMenuMain(int offestX, int offsetY, SpriteFont font, Texture2D buttonIndicator, SoundEffectInstance switchSound, SoundEffectInstance selectSound)
        {
            Name = "Main";
            // Initialize the button list with button indicator and padding between buttons
            ButtonList = new ButtonList(buttonIndicator, offestX, offsetY, font, 50);
            this.switchSound = switchSound;
            this.selectSound = selectSound;
        }
        public override void Enter(object owner)
        {
            LoadMainButtons();
        }
        public override void Exit(object owner)
        {
            ButtonList.Clear();
        }
        public override void Execute(object owner, GameTime gameTime)
        {
            ButtonList.Update();
        }
        private void LoadMainButtons()
        {
            ButtonList.AddButton("Start");
            ButtonList.AddButton("High Scores");
            ButtonList.AddButton("Controls");
            ButtonList.AddButton("Exit");
            // Handle button selection
            ButtonList.ButtonClicked += this.HandleButtonSelection;
            // Play sound on button switch
            ButtonList.ButtonSwitched += (object sender, EventArgs e) => { switchSound.Play(); };
        }
        public override void Draw(object owner, GameTime gameTime, SpriteBatch spriteBatch = null)
        {
            ButtonList.Draw(spriteBatch);
        }
        private void HandleButtonSelection(object sender, Button button)
        {
            // Handle the button selection based on the name of the button
            switch (button.GetText())
            {
                case "Start":
                    GameStart(this, EventArgs.Empty);
                    break;
                case "High Scores":
                    HighScores(this, EventArgs.Empty);
                    break;
                case "Controls":
                    Controls(this, EventArgs.Empty);
                    break;
                case "Exit":
                    ExitGame(this, EventArgs.Empty);
                    break;
                default:
                    break;
            }
            // Play the sound effect related to the select button
            selectSound.Play();
        }
    }
}
